### ISSUE TITLE
Crash under heavy load or after 1/2 day of tailing

### ISSUE THREAD

**Issue by keithknott26** [papertrail/go-tail#9]
Hello, 

My application is crashing after being left for a long period of time (half a day-1 day), it seems to happen when the file is processing high volumes (900+/lines per second). This is on a AMD64 linux system and shows the crash is always a tunix.EpollWait inside fsnotify. Have you seen this before or can recommend a fix?

Also if you need any more detailed information I'm happy to provide it

```
github.com/papertrail/go-tail/vendor/golang.org/x/sys/unix.EpollWait(0x9, 0xc001877d14, 0x7, 0x7, 0xffffffffffffffff, 0xc00b220168, 0xc001877df4, 0xc001312600)
	/Users/keithknott/go/src/github.com/papertrail/go-tail/vendor/golang.org/x/sys/unix/zsyscall_linux_amd64.go:1220 +0x72
github.com/papertrail/go-tail/vendor/github.com/fsnotify/fsnotify.(*fdPoller).wait(0xc0000141a0, 0xc001877d00, 0x2, 0x0)
	/Users/keithknott/go/src/github.com/papertrail/go-tail/vendor/github.com/fsnotify/fsnotify/inotify_poller.go:86 +0x91
github.com/papertrail/go-tail/vendor/github.com/fsnotify/fsnotify.(*Watcher).readEvents(0xc0001b4be0)
	/Users/keithknott/go/src/github.com/papertrail/go-tail/vendor/github.com/fsnotify/fsnotify/inotify.go:192 +0x18a
created by github.com/papertrail/go-tail/vendor/github.com/fsnotify/fsnotify.NewWatcher
	/Users/keithknott/go/src/github.com/papertrail/go-tail/vendor/github.com/fsnotify/fsnotify/inotify.go:61 +0x1e2

goroutine 53 [select]:
github.com/papertrail/go-tail/follower.(*Follower).watchFileEvents(0xc001802c80, 0xc001846000, 0xc0005bed80)
	/Users/keithknott/go/src/github.com/papertrail/go-tail/follower/follower.go:294 +0xe8
created by github.com/papertrail/go-tail/follower.(*Follower).follow
	/Users/keithknott/go/src/github.com/papertrail/go-tail/follower/follower.go:111 +0x193
```

**Comment by keithknott26** [comment]
I've been using this now for a while in production and things work fine. I did update the reopen code so that it waits a bit longer before trying to reopen the file once a move or rename was detected. 

Closing as non-issue.
